version: '3.3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sdfWfwef23f24ffe2332rFEWfwytrhg
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: [ "celery", "-A", "core", "worker", "--loglevel=info" ]
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env

  celerybeat:
    build: .
    command: [ "celery", "-A", "core", "beat", "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler" ]
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  postgres_data: